### ISSUE TITLE
needs to be renamed

### ISSUE THREAD

**Issue by willkg** [mozilla/socorro_pidgeon#1]
I mentioned this in email already, so I think we're all on the same page, but for the purposes of issue tracking, I'm writing it down here.

Socorro already has a major component named "processor", so naming this "processor" confuses things. For example, here's the flow diagram:

```
ANTENNA -> [S3] -> PROCESSOR -> [RABBITMQ] -> PROCESSOR
```

I suggested in the email the following possibilities mostly to kick up some ideas:

* socorro-declare
* socorro-notifier
* socorro-post
* socorro-proclaim
* fred
* miles-under-a-palmtree

@relud suggested I pick a name and he'd rename it. After mulling over it for an exorbitant amount of time, I decided "socorro-pigeon" seemed nice.

Thus the flow diagram becomes:

```
ANTENNA -> [S3] -> PIGEON -> [RABBITMQ] -> PROCESSOR
```

**Comment by relud** [comment]
this is resolved
